import os
import smtplib
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import dotenv_values

# Load environment variables from the .env file, with fallback to OS env vars (for GitHub Actions)
env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'phase2_theme_discovery', '.env')
config = dotenv_values(env_path) if os.path.exists(env_path) else {}

def get_config(key):
    """Get config from .env file first, then fall back to OS environment variables (GitHub Actions)."""
    return config.get(key) or os.environ.get(key)

def load_markdown(filepath):
    """Load the weekly pulse markdown file."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Weekly pulse file not found: {filepath}")
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def markdown_to_html(md_content):
    """
    Convert Markdown to a styled HTML email body.
    Uses the `markdown` library for conversion and wraps the output in a professional email template.
    """
    html_body = markdown.markdown(md_content, extensions=['extra', 'sane_lists'])
    
    # Wrap in a professional email template
    html_email = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333333;
                max-width: 700px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f9f9f9;
            }}
            .email-container {{
                background-color: #ffffff;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
            }}
            h1 {{
                color: #00d09c; /* Groww's brand green */
                border-bottom: 3px solid #00d09c;
                padding-bottom: 10px;
                font-size: 24px;
            }}
            h2 {{
                color: #44475a;
                margin-top: 25px;
                font-size: 18px;
            }}
            ul {{
                padding-left: 20px;
            }}
            li {{
                margin-bottom: 8px;
            }}
            ol {{
                padding-left: 20px;
            }}
            ol li {{
                margin-bottom: 12px;
            }}
            strong {{
                color: #2c2c54;
            }}
            em {{
                color: #666666;
            }}
            blockquote {{
                border-left: 4px solid #00d09c;
                margin: 10px 0;
                padding: 10px 20px;
                background-color: #f0faf7;
                font-style: italic;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 15px;
                border-top: 1px solid #eeeeee;
                font-size: 12px;
                color: #999999;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        <div class="email-container">
            <p>Hello!</p>
            <p>This is the weekly pulse from Groww app. The reviews are taken from Play Store and this report updates every week to give you a snapshot of user sentiment.</p>
            <div style="margin: 20px 0; border-bottom: 1px solid #eeeeee;"></div>
            {html_body}
            <div class="footer">
                <p>This report was auto-generated by the Groww Weekly Pulse pipeline.</p>
                <p>Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html_email

def send_email(html_content, subject=None):
    """
    Send (or draft) the weekly pulse email via SMTP.
    Uses Gmail SMTP by default. Requires an App Password for Gmail.
    """
    sender_email = get_config("EMAIL_SENDER")
    sender_password = get_config("EMAIL_PASSWORD")
    receiver_email = get_config("EMAIL_RECEIVER")
    
    if sender_email: sender_email = sender_email.strip()
    if sender_password: sender_password = sender_password.strip()
    if receiver_email: receiver_email = receiver_email.strip()
    
    if not sender_email or not sender_password or not receiver_email:
        print("\n[WARNING] Email credentials not configured in .env file.")
        print("To send emails, add the following to your .env:")
        print("  EMAIL_SENDER=your_email@gmail.com")
        print("  EMAIL_PASSWORD=your_app_password")
        print("  EMAIL_RECEIVER=recipient@example.com")
        print("\nSaving the HTML email locally instead...")
        return False
    
    # Generate subject line with week number
    if not subject:
        week_num = datetime.now().isocalendar()[1]
        subject = f"[Weekly Pulse] Groww User Sentiment - Wk {week_num}"
    
    # Create email
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = sender_email
    msg['To'] = receiver_email
    
    # Attach plain text fallback and the HTML version
    plain_text = "Please view this email in an HTML-compatible email client."
    msg.attach(MIMEText(plain_text, 'plain', 'utf-8'))
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))
    
    try:
        print(f"Connecting to SMTP server...")
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, msg.as_string())
        print(f"[SUCCESS] Email sent successfully to {receiver_email}!")
        return True
    except Exception as e:
        print(f"[FAILED] Failed to send email: {e}")
        return False

if __name__ == "__main__":
    print("Starting Phase 4: Email Delivery")
    
    # Load the weekly pulse markdown from Phase 3
    pulse_path = os.path.join(os.path.dirname(__file__), "..", "phase3_note_generation", "weekly_pulse.md")
    
    try:
        md_content = load_markdown(pulse_path)
        print("Loaded weekly_pulse.md successfully.")
        
        # Convert markdown to styled HTML
        html_content = markdown_to_html(md_content)
        print("Converted Markdown to HTML email.")
        
        # Save the HTML locally (always, as a backup)
        html_output = os.path.join(os.path.dirname(__file__), "weekly_pulse_email.html")
        with open(html_output, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"Saved HTML email to: {html_output}")
        
        # Attempt to send the email
        email_sent = send_email(html_content)
        
        if not email_sent:
            print(f"\n[INFO] Email was not sent but the HTML file is saved at:\n   {html_output}")
            print("   You can open this file in a browser to preview the email.")
            
    except Exception as e:
        print(f"Fatal error: {e}")
